const workouts = {
            fullBody: [
                ["Push-ups", "10-15 reps"],
                ["Squats", "15-20 reps"],
                ["Dumbbell Rows", "10-12 reps each arm"],
                ["Lunges", "10-12 reps each leg"],
                ["Shoulder Press", "10-12 reps"],
                ["Plank", "30-60 seconds"],
                ["Burpees", "10 reps"],
                ["Bicycle Crunches", "20 reps"],
                ["Dips", "10-15 reps"],
                ["Mountain Climbers", "30 seconds"],
                ["Hex Bar Deadlift", "8-10 reps"],
                ["Hang Clean to Overhead Press", "8-10 reps",],
                ["Kettlebell Clean to Ascending Overhead Press", "1-5 reps",],
                ["Dumbbell Plank and Hip Flexor Step Through", "60 seconds",],
                ["Superman Plank Ball Touch", "30 seconds",],
                ["Forward Overhead Lunge With Rotation", "10-12 reps",],
                ["Kettlebell Plank to Hip Flexor Stretch", "5 per side",]
                ["Barbell Bench Press", "8-10 reps"],
                ["Kettlebell Front Squat", "8-10 reps"],
                ["Standing Alternating Arm Dumbbell Shoulder Press", "5-8 reps per arm"],
                ["Chin-Up", "5-8 reps"],
                ["Walking Dumbbell Lunges", "20 steps total"],
                ["Suspension Trainer Depth Drop to Muscle Overhead", "45 seconds"],
                ["Bodyweight Squat", "15-20 reps"],
                ["Dumbbell 3-Second Pause Chest Press", "8-10 reps"],
                ["Standing Cable Row", "15-20 reps"],
            ],
            upperBody: [
                ["Push-ups", "12-15 reps"],
                ["Dumbbell Rows", "10-12 reps each arm"],
                ["Shoulder Press", "10-12 reps"],
                ["Tricep Dips", "10-15 reps"],
                ["Bicep Curls", "10-12 reps"],
                ["Pull-ups or Assisted Pull-ups", "5-10 reps"],
                ["Lateral Raises", "10-12 reps"],
                ["Diamond Push-ups", "8-10 reps"],
                ["Hammer Curls", "10-12 reps"],
                ["Plank to Downward Dog", "10 reps"],
                ["Dumbbell Rows", "10-12 reps each arm"],
                ["Shoulder Press", "10-12 reps"],
                ["Tricep Dips", "10-15 reps"],
                ["Bicep Curls", "10-12 reps"],
                ["Pull-ups or Assisted Pull-ups", "5-10 reps"],
                ["Lateral Raises", "10-12 reps"],
                ["Diamond Push-ups", "8-10 reps"],
                ["Hammer Curls", "10-12 reps"],
                ["Straight Bar Cable Triceps Pressdown", "15 reps",],
                ["Bodyweight Skull Crusher", "10-12 reps",],
                ["Seated Reclined Double Biceps Curl", "8-10 reps",],
                ["Reverse Grip Triceps Band Pressdown", "15 reps",],
                ["Triceps Band Pressdown", "8-10 reps",],
                ["Alternating Bottom Half Hammer Curl with Hold", "8-10 per side",],
                ["Alternating Biceps Curl with Top Hold", "10 per arm",],
                ["Mid Cable Chest Fly", "8-10 reps",],
                ["Military Grip Pullup", "10 reps",],
                ["Parallel Grip Pull-Up", "10 reps",],
                ["Dumbbell Skull Crusher", "8-10 reps",],
                ["External Band Rotation", "10-12 reps",],
                ["Standing Underhand Cable Row", "15 reps",],
                ["Dumbbell Shrug", "15 reps",],
                ["Banded Dumbbell Biceps Curl", "8-10 reps",],
                ["Wall Curl", "8-10 reps",],
                ["Incline Dumbbell Chest Press", "5-8 reps",],
                ["High Cable Chest Fly", "8-10 reps",],
                ["Wide Grip W Bar Triceps Press Down", "8-10 reps",],
                ["Strict Overhead Barbell Press", "20 reps",],
                ["Single Arm Alternating Lateral Shoulder Raise with Top Hold", "10 per arm",],
                ["Rear Delt Raise", "15 reps",],
                ["Triceps Rope Pressdown", "8-10 reps",],
                ["Equalizer Skull Crusher", "10-12 reps",],
                ["Incline Dumbbell Chest Fly", "8-10 reps",],
                ["Single Single Double Incline Dumbbell Chest Press", "5-8 reps",],
                ["Close Grip Incline Bench Push-up", "15 reps",],
                ["Lateral Band Step Biceps Curl", "8-10 reps",],
                ["Cable Rope Pulldown", "10-12 reps",],
                ["Barbell Shrug", "20 reps",],
            ],
            lowerBody: [
                ["Squats", "15-20 reps"],
                ["Lunges", "10-12 reps each leg"],
                ["Deadlifts", "10-12 reps"],
                ["Calf Raises", "15-20 reps"],
                ["Glute Bridges", "15-20 reps"],
                ["Step-ups", "10-12 reps each leg"],
                ["Wall Sit", "30-60 seconds"],
                ["Sumo Squats", "15-20 reps"],
                ["Single-Leg Deadlifts", "8-10 reps each leg"],
                ["Jump Squats", "10-15 reps"],
                ["Hex Bar Deadlift", "8-10 reps"],
                ["Lateral Band Steps", "15-20 steps each side"],
                ["Standing Calf Raise", "15-20 reps"],
                ["Dumbbell Goblet Squat", "8-10 reps",],
                ["Reverse Alternating Barbell Lunge", "16 reps",],
                ["Forward Alternating Barbell Lunge", "16 reps",],
                ["Pendulum Barbell Lunge", "8-10 per leg",],
                ["Elevated Dumbbell Goblet Squat Circuit", "5 reps in each position",],
                ["Elevated Kettlebell Deadlift", "15-20 reps",]
                ["Barbell Front Squat", "8-10 reps"],
                ["Kettlebell Front Squat", "10-12 reps"],
                ["Walking Dumbbell Lunges", "20 steps total"],
                ["Fixed Bent Knee Standing Calf Raises", "15-20 reps"],
                ["Alternating Single Leg RDL Row", "8-10 reps each leg"],
                ["Bodyweight Squat", "15-20 reps"],
                ["Elevated Heel Bodyweight Squat", "15-20 reps"],
            ],
            core: [
                ["Plank", "30-60 seconds"],
                ["Bicycle Crunches", "20 reps"],
                ["Russian Twists", "20 reps"],
                ["Leg Raises", "15 reps"],
                ["Mountain Climbers", "30 seconds"],
                ["Side Plank", "30 seconds each side"],
                ["Reverse Crunches", "15 reps"],
                ["Flutter Kicks", "20 seconds"],
                ["Dead Bug", "10 reps each side"],
                ["Plank Jacks", "20 reps"],
                ["Seated Knee Tuck", "15 reps"],
                ["V-Ups", "12 reps"],
                ["Jack Knife", "12 reps"],
                ["Toe Touches", "20 reps"],
                ["Butterfly Sit Ups", "15 reps"],
                ["Sprinter Sit Ups", "10 reps each side"],
                ["6 Inch Holds", "30 seconds"],
                ["Table Top Leg Press", "15 reps each leg"],
                ["Bird Dog", "10 reps each side"],
                ["Oblique Crunch", "15 reps each side"],
                ["Alt Jack Knife", "10 reps each side"],
                ["Plank Dips", "10 reps each side"],
                ["Trunk Rotation", "20 reps"],
                ["Bent Knee Wipers", "10 reps each side"],
                ["Alt. Lunge Rotation", "10 reps each side"],
                ["Half Kneeling Rotational Chop", "10 reps each side"],
                ["Bicycles", "30 seconds"],
                ["Cross Mountain Climbers", "30 seconds"],
                ["Pull Over Twist", "12 reps"],
                ["Hollow Body Hold", "30 seconds"],
                ["Superman", "15 reps"],
                ["Scissor Kicks", "30 seconds"],
                ["Pike Crunch", "15 reps"],
                ["Seated In and Outs", "20 reps"],
                ["Plank to Downward Dog", "10 reps"],
                ["Bird-Dog Crunch", "10 reps each side"],
                ["Forearm Plank Rock", "30 seconds"],
                ["Bear Crawl Hold", "30 seconds"],
                ["Lying Leg Raises", "15 reps"],
                ["Alternating Toe Touches", "20 reps"],
                ["Plank Hip Dips", "20 reps"],
                ["Roll-Up", "10 reps"],
                ["Oblique V-Ups", "10 reps each side"],
                ["Windshield Wipers", "10 reps each side"],
                ["Plank Knee to Elbow", "10 reps each side"],
                ["Side Plank with Hip Lift", "10 reps each side"],
                ["Reverse Plank", "30 seconds"],
                ["Spiderman Plank", "10 reps each side"]
                ["Forearm Plank With Lateral Skip", "30 seconds"],
                ["Equalizer Dip to Knee Tuck", "10 reps"],
                ["Equalizer Dip to L Sit", "8 reps"],
                ["Suspension Overhead Oblique Bend", "10 reps each side"],
                ["Bird Dog Plank Pushup", "8 reps each side"],
                ["Plank Pushup To Side Plank", "10 reps total"],
                ["Close Grip Push Up with Alternating Side Plank Punch", "10 reps total"],
                ["Suspension Oblique to Overhead with Single Arm", "8 reps each side"],
                ["Suspension Mobility Rotation", "10 reps each side"],
            ],
            hiit: [
                ["Burpees", "10 reps"],
                ["High Knees", "30 seconds"],
                ["Jumping Jacks", "30 seconds"],
                ["Mountain Climbers", "30 seconds"],
                ["Jump Squats", "15 reps"],
                ["Plank Jacks", "20 reps"],
                ["Skater Hops", "20 reps"],
                ["Squat Thrusts", "10 reps"],
                ["Alternating Lunge Jumps", "20 reps"],
                ["Tuck Jumps", "10 reps"],
                ["Kettlebell Deadlift Burpee", "45 seconds", "Challenge"],
                ["Medial-Lateral Plyo Bench Push-Up", "10-12 reps",],
                ["Plank Push Up", "15 reps",],
                ["Single Dumbbell Row To Goblet Curl", "8-10 reps",],
                ["Slam Ball Rotation Burpee Flow", "10 full sequences per side",],
                ["Kettlebell Low Clean Squat Complex", "10 complete sequences",],
                ["Pushup Breakdown Flow", "As shown in video",],
                ["Walking Lunge With Rotation", "16 reps",],
                ["Renegade Row Burpee Biceps Curl", "8-10 reps",],
                ["Ascending Close Grip Pushup to Side Plank Punch", "1-5 per side",],
                ["Kettlebell Clean to Overhead Press Burpee Flow", "As shown in video",],
                ["Slam Ball Burpee with Ascending Overhead Press", "8 reps"],
                ["Suspension Trainer Depth Drop to Muscle Overhead", "45 seconds"],
                ["Equalizer Chest Fly Push Up", "10 reps"],
                ["Equalizer Muscle Up", "5 reps"],
                ["Incline EQ Pushup with Descending Knee Tuck", "10 reps"],
                ["Bird Dog Plank Pushup", "8 reps each side"],
                ["Close Grip Push Up with Alternating Side Plank Punch", "10 reps total"],
                ["Hang Clean to Ascending Overhead Press Ladder", "5 reps"],
                ["Suspension Lever Squat To Overhead T Squat", "10 reps"],
            ]
        };

        const warmups = [
            ["Arm Circles", "10 forward, 10 backward"],
            ["Leg Swings", "10 each leg"],
            ["Torso Twists", "10 each side"],
            ["Jumping Jacks", "20 reps"],
            ["High Knees", "30 seconds"],
            ["Bodyweight Squats", "10 reps"],
            ["Walking Lunges", "10 each leg"],
            ["Hip Rotations", "10 each direction"],
            ["Shoulder Rolls", "10 forward, 10 backward"],
            ["Butt Kicks", "30 seconds"],
        ];

export { workouts, warmups };