export const workouts = {
            fullBody: [
                ["Push-ups", "10-15 reps"],
                ["Squats", "15-20 reps"],
                ["Dumbbell Rows", "10-12 reps each arm"],
                ["Lunges", "10-12 reps each leg"],
                ["Reverse Lunges", "10-12 reps each leg"],
                ["Shoulder Press", "10-12 reps"],
                ["Plank", "60 seconds"],
                ["Burpees", "10 reps"],
                ["Bicycle Crunches", "20 reps"],
                ["Dips", "10-15 reps"],
                ["Mountain Climbers", "30 seconds"],
                ["Hex Bar Deadlift", "8-10 reps"],
                ["Hang Clean to Overhead Press", "8-10 reps"],
                ["Kettlebell Clean to Overhead Press", "1-5 reps"],
                ["Dumbbell Plank and Hip Flexor Step Through", "60 seconds"],
                ["Superman Plank Ball Touch", "30 seconds"],
                ["Forward Overhead Lunge With Rotation", "10-12 reps"],
                ["Kettlebell Plank to Hip Flexor Stretch", "5 per side"],
                ["Barbell Bench Press", "8-10 reps"],
                ["Kettlebell Front Squat", "8-10 reps"],
                ["Standing Alternating Arm Dumbbell Shoulder Press", "5-8 reps per arm"],
                ["Chin-Up", "5-8 reps"],
                ["Neatral grip pull up", "5-8 reps"],      
                ["Walking Dumbbell Lunges", "20 steps total"],
                ["Dumbbell 3-Second Pause Chest Press", "8-10 reps"],
                ["Standing Cable Row", "15-20 reps"],
            ],
            upperBody: [
                ["Push-ups", "12-15 reps"],
                ["Dumbbell Rows", "10-12 reps each arm"],
                ["Shoulder Press", "10-12 reps"],
                ["Tricep Dips", "10-15 reps"],
                ["Bicep Curls", "10-12 reps"],
                ["Pull-ups", "5-10 reps"],
                ["Lateral Raises", "10-12 reps"],
                ["Diamond Push-ups", "8-10 reps"],
                ["Hammer Curls", "10-12 reps"],
                ["Dumbbell Rows", "10-12 reps each arm"],
                ["Shoulder Press", "10-12 reps"],
                ["Tricep Dips", "10-15 reps"],
                ["Straight Bar Cable Triceps Pressdown", "15 reps",],
                ["Bodyweight Skull Crusher", "10-12 reps",],
                ["Seated Reclined Double Biceps Curl", "8-10 reps",],
                ["Alternating Bottom Half Hammer Curl with Hold", "8-10 per side",],
                ["Alternating Biceps Curl with Top Hold", "10 per arm",],
                ["Mid Cable Chest Fly", "8-10 reps",],
                ["Military Grip Pullup", "10 reps",],
                ["Parallel Grip Pull-Up", "10 reps",],
                ["Dumbbell Skull Crusher", "8-10 reps",],
                ["External Band Rotation", "10-12 reps",],
                ["Standing Underhand Cable Row", "15 reps",],
                ["Dumbbell Shrug", "15 reps",],
                ["Incline Dumbbell Chest Press", "5-8 reps",],
                ["High Cable Chest Fly", "8-10 reps",],
                ["Wide Grip W Bar Triceps Press Down", "8-10 reps",],
                ["Strict Overhead Barbell Press", "20 reps",],
                ["Single Arm Alternating Lateral Shoulder Raise with Top Hold", "10 per arm",],
                ["Rear Delt Raise", "15 reps",],
                ["Triceps Rope Pressdown", "8-10 reps",],
                ["Equalizer Skull Crusher", "10-12 reps",],
                ["Incline Dumbbell Chest Fly", "8-10 reps",],
                ["Single Single Double Incline Dumbbell Chest Press", "5-8 reps",],
                ["Close Grip Incline Bench Push-up", "15 reps",],
                ["Cable Rope Pulldown", "10-12 reps",],
                ["Barbell Shrug", "20 reps",],
            ],
            lowerBody: [
                ["Squats", "15-20 reps"],
                ["Lunges", "10-12 reps each leg"],
                ["Deadlifts", "10-12 reps"],
                ["Calf Raises", "15-20 reps"],
                ["Glute Bridges", "15-20 reps"],
                ["Single leg glute Bridges", "15-20 reps"],       
                ["Step-ups", "10-12 reps each leg"],
                ["Wall Sit", "30-60 seconds"],
                ["Sumo Squats", "15-20 reps"],
                ["Single-Leg Deadlifts", "8-10 reps each leg"],
                ["Jump Squats", "10-15 reps"],
                ["Hex Bar Deadlift", "8-10 reps"],
                ["Lateral Band Steps", "15-20 steps each side"],
                ["Standing Calf Raise", "15-20 reps"],
                ["Dumbbell Goblet Squat", "8-10 reps"],
                ["Reverse Alternating Barbell Lunge", "16 reps"],
                ["Forward Alternating Barbell Lunge", "16 reps"],
                ["Pendulum Barbell Lunge", "8-10 per leg"],
                ["Elevated Dumbbell Goblet Squat", "5 reps"],
                ["Elevated Kettlebell Deadlift", "15-20 reps"],
                ["Barbell Front Squat", "8-10 reps"],
                ["Kettlebell Front Squat", "10-12 reps"],
                ["Walking Dumbbell Lunges", "20 steps total"],
                ["Fixed Bent Knee Standing Calf Raises", "15-20 reps"],
                ["Elevated Heel Bodyweight Squat", "15-20 reps"],
            ],
            core: [
                ["Plank", "30-60 seconds"],
                ["Bicycle Crunches", "20 reps"],
                ["Russian Twists", "20 reps"],
                ["Leg Raises", "15 reps"],
                ["Mountain Climbers", "30 seconds"],
                ["Side Plank", "30 seconds each side"],
                ["Reverse Crunches", "15 reps"],
                ["Flutter Kicks", "20 seconds"],
                ["Dead Bug", "10 reps each side"],
                ["Plank Jacks", "20 reps"],
                ["Seated Knee Tuck", "15 reps"],
                ["V-Ups", "12 reps"],
                ["Jack Knife", "12 reps"],
                ["Toe Touches", "20 reps"],
                ["Butterfly Sit Ups", "15 reps"],
                ["Sprinter Sit Ups", "10 reps each side"],
                ["6 Inch Holds", "30 seconds"],
                ["Bird Dog", "10 reps each side"],
                ["Oblique Crunch", "15 reps each side"],
                ["Alt Jack Knife", "10 reps each side"],
                ["Plank Dips", "10 reps each side"],
                ["Trunk Rotation", "20 reps"],
                ["Bent Knee Wipers", "10 reps each side"],
                ["Cross Mountain Climbers", "30 seconds"],
                ["Hollow Body Hold", "30 seconds"],
                ["Superman", "15 reps"],
                ["Scissor Kicks", "30 seconds"],
                ["Pike Crunch", "15 reps"],
                ["Seated In and Outs", "20 reps"],
                ["Plank to Downward Dog", "10 reps"],
                ["Forearm Plank Rock", "30 seconds"],
                ["Bear Crawl", "30 seconds"],
                ["Lying Leg Raises", "15 reps"],
                ["Alternating Toe Touches", "20 reps"],
                ["Oblique V-Ups", "10 reps each side"],
                ["Windshield Wipers", "10 reps each side"],
                ["Plank Knee to Elbow", "10 reps each side"],
                ["Reverse Plank", "30 seconds"],
                ["Forearm Plank With Lateral Skip", "30 seconds"],
                ["Equalizer Dip to Knee Tuck", "10 reps"],
                ["Equalizer Dip to L Sit", "8 reps"],
                ["Bird Dog Plank Pushup", "8 reps each side"],
                ["Plank Pushup To Side Plank", "10 reps total"],
            ],
            hiit: [
                ["Burpees", "10 reps"],
                ["High Knees", "30 seconds"],
                ["Jumping Jacks", "30 seconds"],
                ["Mountain Climbers", "30 seconds"],
                ["Jump Squats", "15 reps"],
                ["Plank Jacks", "20 reps"],
                ["Skater Hops", "20 reps"],
                ["Squat Thrusts", "10 reps"],
                ["Alternating Lunge Jumps", "20 reps"],
                ["Plank Push Up", "15 reps"],
                ["Slam Ball Rotation Burpee Flow", "10 full sequences per side"],
                ["Walking Lunge With Rotation", "16 reps"],
                ["Renegade Row Burpee Biceps Curl", "8-10 reps"],
                ["Ascending Close Grip Pushup to Side Plank Punch", "1-5 per side"],
                ["Kettlebell Clean to Overhead Press Burpee Flow", "As shown in video"],
                ["Slam Ball Burpee with Ascending Overhead Press", "8 reps"],
                ["Equalizer Chest Fly Push Up", "10 reps"],
                ["Bird Dog Plank Pushup", "8 reps each side"],
            ]
        };

export const warmups = [
            ["Arm Circles", "10 forward, 10 backward"],
            ["Leg Swings", "10 each leg"],
            ["Torso Twists", "10 each side"],
            ["Jumping Jacks", "20 reps"],
            ["High Knees", "30 seconds"],
            ["Bodyweight Squats", "10 reps"],
            ["Walking Lunges", "10 each leg"],
            ["Hip Rotations", "10 each direction"],
            ["Shoulder Rolls", "10 forward, 10 backward"],
            ["Butt Kicks", "30 seconds"],
        ];
function validateWorkouts(workouts) {
  for (const [type, exercises] of Object.entries(workouts)) {
    if (!Array.isArray(exercises)) {
      console.error(`Invalid workout type: ${type}`);
      continue;
    }
    exercises.forEach((exercise, index) => {
      if (!Array.isArray(exercise) || exercise.length !== 2 || typeof exercise[0] !== 'string' || typeof exercise[1] !== 'string') {
        console.error(`Invalid exercise in ${type} at index ${index}:`, exercise);
      }
    });
  }
}

validateWorkouts(workouts);
